# Basic
name:               "William Denman"
paginate:	    5

title:		    "William Denman"
tagline:	    PhD

# URL
baseurl:            ""
permalink:           pretty
relative_permalinks: true

# Navigation
nav:
  - name:           "About"
    href:           "//ic3guy.github.io/about/"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
      comments:     "true"